# Generated by Django 4.1.5 on 2023-01-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.CharField(blank=True, choices=[('ME', 'Mechanical Engineering'), ('CSE', 'Computer Science Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('EE', 'Electrical Engineering'), ('EPH', 'Engineering Physics'), ('NON', 'others or None of the Above')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='userr@user.com', max_length=254, unique=True),
        ),
    ]
