# Generated by Django 4.1.5 on 2023-01-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vote_1_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='vote_2_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='vote_3_bool',
            field=models.BooleanField(default=False),
        ),
    ]
