# Generated by Django 4.1.5 on 2023-01-13 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_candidate_email'),
        ('users', '0005_user_vote_1_bool_user_vote_2_bool_user_vote_3_bool'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vote_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate1', to='elections.candidate'),
        ),
        migrations.AddField(
            model_name='user',
            name='vote_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate2', to='elections.candidate'),
        ),
        migrations.AddField(
            model_name='user',
            name='vote_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate3', to='elections.candidate'),
        ),
    ]
