# Generated by Django 4.1.5 on 2023-01-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vote_1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vote_2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vote_3',
        ),
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.CharField(blank=True, choices=[('First', '1'), ('Second', '2'), ('Third', '3'), ('Fourth', '4')], max_length=50, null=True),
        ),
    ]
