# Generated by Django 4.1.5 on 2023-01-14 12:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('date', models.DateField(default=datetime.date(2023, 1, 14))),
                ('time', models.TimeField(default=datetime.datetime(2023, 1, 14, 17, 49, 50, 870856))),
                ('duration', models.CharField(max_length=50)),
                ('yop', models.CharField(choices=[('First Year', '1'), ('Second Year', '2'), ('Third Year', '3'), ('Fourth Year', '4')], max_length=50)),
                ('branch', models.CharField(blank=True, choices=[('Mechanical Engineering', 'ME'), ('Computer Science Engineering', 'CSE'), ('Electronics and Communication Engineering', 'ECE'), ('Electrical Engineering', 'EE'), ('Engineering Physics', 'EPH'), ('Civil Enginnering', 'CE'), ('Chemical Engineering', 'CHE'), ('Mathematics and Computing', 'MNC'), ('Metallurgy and Material sciences', 'META'), ('NON', 'others or None of the Above')], max_length=50, null=True)),
                ('description', models.CharField(max_length=10000)),
                ('mobile', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue', to='events.venue')),
            ],
        ),
    ]
