# Generated by Django 4.1.5 on 2023-01-14 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='branch',
            field=models.CharField(blank=True, choices=[('ME', 'Mechanical Engineering'), ('Computer Science Engineering', 'CSE'), ('Electronics and Communication Engineering', 'ECE'), ('Electrical Engineering', 'EE'), ('Engineering Physics', 'EPH'), ('Civil Enginnering', 'CE'), ('Chemical Engineering', 'CHE'), ('Mathematics and Computing', 'MNC'), ('Metallurgy and Material sciences', 'META'), ('NON', 'others or None of the Above')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 14, 22, 33, 7, 32266)),
        ),
    ]
