# Generated by Django 4.1.5 on 2023-01-14 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_branch_alter_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='manager',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(default=datetime.date(2023, 1, 15)),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.TimeField(default=datetime.datetime(2023, 1, 15, 0, 4, 20, 55307)),
        ),
    ]
