# Generated by Django 4.1.5 on 2023-01-14 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_event_manager_alter_event_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
    ]
