# Generated by Django 4.1.5 on 2023-01-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='vote_1',
        ),
        migrations.AddField(
            model_name='voter',
            name='vote_2_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='vote_3_bool',
            field=models.BooleanField(default=False),
        ),
    ]
