# Generated by Django 4.1.5 on 2023-01-13 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_remove_voter_vote_1_voter_vote_2_bool_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voter',
        ),
    ]
