# Generated by Django 4.1.5 on 2023-01-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_candidate_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
