# Generated by Django 4.1.5 on 2023-01-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_candidate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='year',
            field=models.CharField(blank=True, choices=[('First', '1'), ('Second', '2'), ('Third', '3'), ('Fourth', '4')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='bio',
            field=models.CharField(max_length=5000),
        ),
    ]
